# Site settings
name: alpha1e0
title: "alpha1e0's blog"
email: yan.shifm@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  hacking for fun
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alpha1e0.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  alpha1e0

# Build settings
markdown: kramdown
