# Site settings
title: Git site of alpha1e0
email: yan.shifm@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  alpha1e0. hacking for fun. hacking for future.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alpha1e0.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  alpha1e0

# Build settings
markdown: kramdown
